app:
  name: chassix-bootstrap-example
  version: 1.1.0
  env: dev
  debug: no
server:
  port: 8000
  addr: 0.0.0.0
logging:
  level: info  #0 panic 0 fatal 1 error 2 warn 3 info 4 debug 5 trace 6
  report-caller: yes
  no-colors: false
  caller-first: no